name: 'build'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'release'
    runs-on: ubuntu-latest
    env:
      ALPINE: '3.14'
      PGBACKREST: '2.35'
      POSTGRESQL: '13.4'
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: 'checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'login'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'setup buildx'
        uses: docker/setup-buildx-action@v1

      - name: 'build'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64 #,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ env.POSTGRESQL }}-${{ env.PGBACKREST }}-${{ env.ALPINE}}-${{ steps.date.outputs.date }}
          build-args: |
            ALPINE=${{ env.ALPINE }}
            PGBACKREST=${{ env.PGBACKREST }}
            POSTGRESQL=${{ env.POSTGRESQL }}
